version: "3"

networks:
  monitoring:

volumes:
  prometheus:
  grafana:

services:
  loki:
    image: grafana/loki:v1.3.0
    restart: unless-stopped
    volumes:
      - ./loki.yaml:/etc/loki/config.yaml
      - /var/log:/var/log
    command: -config.file=/etc/loki/config.yaml
    ports: ["3100:3100"]
    networks: [monitoring]
    logging:
      driver: json-file

  vector:
    image: timberio/vector:0.11.X-alpine
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./vector.toml:/etc/vector/vector.toml:ro
    ports: ["8383:8383", "1514:1514/udp"]
    networks: [monitoring]

  grafana:
    image: grafana/grafana:7.1.5
    restart: unless-stopped
    volumes:
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/monitoring.yaml
      - ./dashboards:/etc/grafana/provisioning/dashboards
      - grafana:/var/lib/grafana
    ports: ["3000:3000"]
    networks: [monitoring]

  cadvisor:
    image: gcr.io/google_containers/cadvisor:v0.36.0
    restart: unless-stopped
    command: --docker_only=true --store_container_labels=false
    ports: ["9081:8080"]
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks: [monitoring]
    privileged: true

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports: ["6831:6831/udp", "6832:6832/udp", "16686:16686"]
    networks: [monitoring]
